name: Déployer l'image Docker stable

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version image (exemple: 0.3)'
        required: true
        default: 'latest'
        type: string

jobs:
  build-and-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t wezzer .

      - name: Tag Docker Image
        run: |
          docker tag wezzer albatros329/wezzer:${{ github.event.inputs.version }}
          docker tag wezzer albatros329/wezzer:latest

      - name: Push Docker Image (version spécifique)
        run: docker push albatros329/wezzer:${{ github.event.inputs.version }}

      - name: Push Docker Image (latest)
        run: docker push albatros329/wezzer:latest
